import { useApolloClient } from '@apollo/client'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { GENERATE_TOKEN } from '../apollo/mutations/generateToken'
import { useLoginUser } from '../hooks/useLoginUser'
import { useLogout } from '../hooks/useLogout'
import styles from '../styles/Home.module.css'


const Home: NextPage | any = () => {
  const {data,loading} = useLoginUser();
  const {logout} = useLogout();

  console.log(data,loading)

  if(loading) return "Loading..."

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>STRONA GłÓWNA</h1>
      <button onClick={logout}>Wyloguj</button>

      {data && <p>{data?.customer?.firstname}</p>}

    </div>
  )
}

export default Home
