import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useLoginUser } from '../hooks/useLoginUser'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const {data} = useLoginUser();
  console.log(data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>STRONA GłÓWNA</h1>
      <button onClick={()=>{
       localStorage.setItem("token","");
      }}>Wyloguj</button>

      {data && <p>{data.customer.firstname}</p>}

    </div>
  )
}

export default Home
